### ISSUE TITLE
Diacritics issues

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/ruthie#8]
Hi @crystaltype. Giving Ruthie the last inspections before PR I found some issues in Ruthie's diacritics. 

**Distance to base letters**

The distance to the base letters is now too high in lower case.
![ruthie-diacritics](https://user-images.githubusercontent.com/48698976/120026050-21af7780-bfb7-11eb-8c10-f46a422126c0.gif)

**Comment by vv-monsalve** [comment]
**Visually centring the diacritics**

(`dieresis` use to be a good key)

As was [pointed in MonteCarlo](https://github.com/googlefonts/monte-carlo/issues/5), the diacritics look shifted a bit to the left. Please ensure that for all of the base letters
![ruthie-diacritics-xalign](https://user-images.githubusercontent.com/48698976/120027930-a13e4600-bfb9-11eb-8186-97c98cb5f544.gif)

**Comment by vv-monsalve** [comment]
**Scaled diacritics**

`grave` used in a proportion. This is leading for it to look smaller than the others, particularly `acute` (a mark that is closely related) and to have not rounded coordinates. Please inspect it to solve both situations.

An observation around using scaled components was done before in [Windsong](https://github.com/googlefonts/windsong/issues/6#issue-893450378)

![Screen Shot 2021-05-28 at 13 25 15](https://user-images.githubusercontent.com/48698976/120028557-70124580-bfba-11eb-8e51-927067d32932.png)
![Screen Shot 2021-05-28 at 13 25 28](https://user-images.githubusercontent.com/48698976/120028565-73a5cc80-bfba-11eb-93c0-f8f8f442a23d.png)
![Screen Shot 2021-05-28 at 13 25 42](https://user-images.githubusercontent.com/48698976/120028577-79031700-bfba-11eb-9965-fcdd44a4b3c5.png)

**Comment by vv-monsalve** [comment]
**Legacy marks consistency**

The `legacy marks` are not consistent with `combining marks`. To ensure consistency between the sets please create the former using the latter as components.


![Screen Shot 2021-05-28 at 13 42 40](https://user-images.githubusercontent.com/48698976/120029425-b1efbb80-bfbb-11eb-9568-a58220015275.png)

**Comment by crystaltype** [comment]
@vv-monsalve Okay, I'm on it, I noted all of these checks and won't let it happen next time!
Thank you!
